# Generated by Django 2.0 on 2018-08-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='author',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(default='/home/sheshant/PycharmProjects/wwstay/wwstay/images/xrSh9Z0.jpg', upload_to='images/'),
        ),
    ]
